tests: add test cov for ALL wal_name* extractors
Issue: #64
Issue: #65
Issue: #66
Issue: #67

tests: adding unit tests for extractors
  * epoch extractors
  * core extractors
  * wal_name parsers
filesystem:wal: only modify files hasmod this core
* only modify files that belong to this core.
bugfix:filesystem: == -> != string::npos match
* is_name_locked method in wal_file_walker.h was incorrectly comparing
  locked vs unlocked files
testing: adding unit tests for all parsing utils
* test for all wal_name* related utils.
* refactored out classes into testable static methods for regexes
* unified all name parsing into 1 utils class
* build: tag seastar includes as SYSTEM's
* currently building release mode fails to compile because
seastar headers are incomplete:

  * posix.hh:459:10: error: unused variable ‘r’
    [-Werror=unused-variable]

  * future.hh:737:5: error: control reaches end of non-void
    function [-Werror=return-type]

* testing: adding repeat test options to runner

* extend runner with:
  - copy_files: globbing capabilities
  - repeat_times - to repeat tests N times
  - repeat_in_same_dir - to re-use the same directory
    useful for stateful operations and crashes

* Add timestamps to wal file names

  * if the wal is `smf0_1234.wal' next time l-core 0 starts up at 1234 epoch
    it will override the same name.
  * This only happens If and only if, the file is empty. Otherwise it will
    move the offset to the correct byte.
  * <id-microsecond>:<l-core-id>:<epoch>.wal:

  -rw-r--r--.  1 agallego       37 Feb 12 13:52 1486925534865633:0:0.wal
  -rw-r--r--.  1 agallego       37 Feb 12 13:52 1486925535699480:0:37.wal
  -rw-r--r--.  1 agallego       37 Feb 12 13:52 1486925536456389:0:74.wal